additional_feature_files: None
base_run_dir: ./runs/Maurer_CAMELS_Every_531_0410_172511
batch_size: 256
cache_validation_data: true
checkpoint_path: None
clip_gradient_norm: 1
commit_hash:
data_dir: .
dataset: generic
device: cuda:0
dynamic_inputs:
- prcp
- srad
- tmax
- tmin
- vp
epochs: 30
evolving_attributes:
experiment_name: Maurer_CAMELS_Every_531
forcings:
head: regression
hidden_size: 256
img_log_dir: ./runs/Maurer_CAMELS_Every_531_0410_172511/img_log
initial_forget_bias: 6
is_continue_training: true
learning_rate:
  0: 0.001
  10: 0.0005
  20: 0.0001
log_interval: 5
log_n_figures:
log_tensorboard: true
loss: NSE
metrics:
- NSE
- KGE
model: ealstm
num_workers: 16
number_of_basins: 531
optimizer: Adam
output_activation: linear
output_dropout: 0.42
package_version: 1.3.0
per_basin_test_periods_file: None
per_basin_train_periods_file: None
per_basin_validation_periods_file: None
predict_last_n: 1
regularization:
run_dir: ./runs/Maurer_CAMELS_Every_531_0410_172511
save_train_data: true
save_validation_results: true
save_weights_every: 1
seed: 42
seq_length: 365
static_attributes:
- elev_mean
- slope_mean
- area_gages2
- frac_forest
- lai_max
- lai_diff
- gvf_max
- gvf_diff
- soil_depth_pelletier
- soil_depth_statsgo
- soil_porosity
- soil_conductivity
- max_water_content
- sand_frac
- silt_frac
- clay_frac
- carbonate_rocks_frac
- geol_permeability
- p_mean
- pet_mean
- aridity
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
target_noise_std:
target_variables:
- QObs
test_basin_file: basin_list_r42.txt
test_end_date: 30/09/1999
test_start_date: 01/10/1989
train_basin_file: basin_list_r42.txt
train_data_file: None
train_dir: ./runs/Maurer_CAMELS_Every_531_0410_172511/train_data
train_end_date: 30/09/2008
train_start_date: 01/10/1999
use_basin_id_encoding: false
validate_every: 3
validate_n_random_basins: 531
validation_basin_file: basin_list_r42.txt
validation_end_date: 30/09/1989
validation_start_date: 01/10/1980
